//! Diagnostic-only GPU coordinate proof and exact emitted lifetime cost census.
use crate::point_add::trailmix_port::circuit::{Circuit,QReg};
use crate::circuit::{Op,OperationType as K};
thread_local!{static PATTERNS:std::cell::RefCell<Vec<Vec<Op>>>=const{std::cell::RefCell::new(Vec::new())};}
pub(super) fn capture(ops:&[Op]){if std::env::var_os("Q792_MEMORY_BUDGET").is_some(){PATTERNS.with(|p|p.borrow_mut().push(ops.to_vec()));}}
thread_local!{static STAGES:std::cell::RefCell<Vec<(&'static str,usize,u64)>>=const{std::cell::RefCell::new(Vec::new())};}
pub(super) fn record_stage(c:&Circuit,name:&'static str){if std::env::var_os("Q792_MEMORY_BUDGET").is_some(){STAGES.with(|s|{let mut s=s.borrow_mut();let at=s.last().map_or(0,|x|x.1);let t=c.b.ops[at..].iter().filter(|o|o.kind==K::CCX).count()as u64;s.push((name,c.b.ops.len(),t));});}}
fn signature(o:&Op)->(u64,u64,u64,u32){(o.q_control1.0,o.q_control2.0,o.q_target.0,o.kind as u32)}
fn coordinate(c:&mut Circuit,q:&[QReg]){assert_eq!(q.len(),9);
c.cx(&q[5],&q[3]);
c.cx(&q[5],&q[1]);
c.cx(&q[3],&q[5]);
c.cx(&q[3],&q[2]);
c.cx(&q[3],&q[1]);
c.cx(&q[2],&q[3]);
c.cx(&q[2],&q[0]);
c.cx(&q[1],&q[5]);
c.cx(&q[1],&q[2]);
c.cx(&q[1],&q[0]);
c.cx(&q[0],&q[2]);
c.cx(&q[0],&q[1]);
c.cx(&q[1],&q[0]);
c.cx(&q[0],&q[1]);
c.x(&q[1]);
c.ccx(&q[0],&q[1],&q[5]);
c.x(&q[1]);
c.cx(&q[0],&q[1]);
c.cx(&q[1],&q[0]);
c.cx(&q[0],&q[1]);
c.cx(&q[0],&q[2]);
c.cx(&q[1],&q[0]);
c.cx(&q[1],&q[2]);
c.cx(&q[1],&q[5]);
c.cx(&q[2],&q[0]);
c.cx(&q[2],&q[3]);
c.cx(&q[3],&q[1]);
c.cx(&q[3],&q[2]);
c.cx(&q[3],&q[5]);
c.cx(&q[5],&q[1]);
c.cx(&q[5],&q[3]);
c.cx(&q[4],&q[3]);
c.cx(&q[4],&q[2]);
c.cx(&q[4],&q[0]);
c.cx(&q[4],&q[5]);
c.cx(&q[5],&q[4]);
c.cx(&q[4],&q[5]);
c.cx(&q[3],&q[5]);
c.cx(&q[3],&q[2]);
c.cx(&q[3],&q[0]);
c.cx(&q[2],&q[3]);
c.cx(&q[3],&q[2]);
c.cx(&q[2],&q[3]);
c.cx(&q[1],&q[2]);
c.cx(&q[2],&q[1]);
c.cx(&q[1],&q[2]);
c.cx(&q[0],&q[5]);
c.cx(&q[0],&q[3]);
c.cx(&q[0],&q[1]);
c.ccx(&q[0],&q[1],&q[5]);
c.cx(&q[0],&q[1]);
c.cx(&q[0],&q[3]);
c.cx(&q[0],&q[5]);
c.cx(&q[1],&q[2]);
c.cx(&q[2],&q[1]);
c.cx(&q[1],&q[2]);
c.cx(&q[2],&q[3]);
c.cx(&q[3],&q[2]);
c.cx(&q[2],&q[3]);
c.cx(&q[3],&q[0]);
c.cx(&q[3],&q[2]);
c.cx(&q[3],&q[5]);
c.cx(&q[4],&q[5]);
c.cx(&q[5],&q[4]);
c.cx(&q[4],&q[5]);
c.cx(&q[4],&q[0]);
c.cx(&q[4],&q[2]);
c.cx(&q[4],&q[3]);
c.cx(&q[4],&q[5]);
c.cx(&q[5],&q[4]);
c.cx(&q[4],&q[5]);
c.cx(&q[3],&q[5]);
c.cx(&q[5],&q[3]);
c.cx(&q[3],&q[5]);
c.cx(&q[2],&q[1]);
c.cx(&q[2],&q[0]);
c.cx(&q[2],&q[5]);
c.cx(&q[5],&q[2]);
c.cx(&q[2],&q[5]);
c.cx(&q[1],&q[5]);
c.cx(&q[1],&q[0]);
c.cx(&q[0],&q[5]);
c.cx(&q[0],&q[1]);
c.x(&q[0]);
c.x(&q[1]);
c.ccx(&q[0],&q[1],&q[5]);
c.x(&q[1]);
c.x(&q[0]);
c.cx(&q[0],&q[1]);
c.cx(&q[0],&q[5]);
c.cx(&q[1],&q[0]);
c.cx(&q[1],&q[5]);
c.cx(&q[2],&q[5]);
c.cx(&q[5],&q[2]);
c.cx(&q[2],&q[5]);
c.cx(&q[2],&q[0]);
c.cx(&q[2],&q[1]);
c.cx(&q[3],&q[5]);
c.cx(&q[5],&q[3]);
c.cx(&q[3],&q[5]);
c.cx(&q[4],&q[5]);
c.cx(&q[5],&q[4]);
c.cx(&q[4],&q[5]);
c.cx(&q[5],&q[4]);
c.cx(&q[5],&q[3]);
c.cx(&q[5],&q[2]);
c.cx(&q[5],&q[1]);
c.cx(&q[5],&q[0]);
c.cx(&q[4],&q[5]);
c.cx(&q[4],&q[3]);
c.cx(&q[4],&q[2]);
c.cx(&q[4],&q[1]);
c.cx(&q[4],&q[0]);
c.cx(&q[3],&q[5]);
c.cx(&q[3],&q[4]);
c.cx(&q[3],&q[2]);
c.cx(&q[3],&q[1]);
c.cx(&q[3],&q[0]);
c.cx(&q[2],&q[5]);
c.cx(&q[2],&q[4]);
c.cx(&q[2],&q[3]);
c.cx(&q[2],&q[1]);
c.cx(&q[2],&q[0]);
c.cx(&q[1],&q[5]);
c.cx(&q[1],&q[4]);
c.cx(&q[1],&q[3]);
c.cx(&q[1],&q[2]);
c.cx(&q[1],&q[0]);
c.cx(&q[0],&q[5]);
c.cx(&q[0],&q[4]);
c.cx(&q[0],&q[3]);
c.cx(&q[0],&q[2]);
c.cx(&q[0],&q[1]);
c.x(&q[1]);
c.x(&q[3]);
c.ccx(&q[0],&q[1],&q[6]);
c.ccx(&q[6],&q[2],&q[7]);
c.ccx(&q[7],&q[3],&q[8]);
c.ccx(&q[8],&q[4],&q[5]);
c.ccx(&q[7],&q[3],&q[8]);
c.ccx(&q[6],&q[2],&q[7]);
c.ccx(&q[0],&q[1],&q[6]);
c.ccx(&q[6],&q[2],&q[7]);
c.ccx(&q[7],&q[3],&q[8]);
c.ccx(&q[8],&q[4],&q[5]);
c.ccx(&q[7],&q[3],&q[8]);
c.ccx(&q[6],&q[2],&q[7]);
c.x(&q[3]);
c.x(&q[1]);
c.cx(&q[0],&q[1]);
c.cx(&q[0],&q[2]);
c.cx(&q[0],&q[3]);
c.cx(&q[0],&q[4]);
c.cx(&q[0],&q[5]);
c.cx(&q[1],&q[0]);
c.cx(&q[1],&q[2]);
c.cx(&q[1],&q[3]);
c.cx(&q[1],&q[4]);
c.cx(&q[1],&q[5]);
c.cx(&q[2],&q[0]);
c.cx(&q[2],&q[1]);
c.cx(&q[2],&q[3]);
c.cx(&q[2],&q[4]);
c.cx(&q[2],&q[5]);
c.cx(&q[3],&q[0]);
c.cx(&q[3],&q[1]);
c.cx(&q[3],&q[2]);
c.cx(&q[3],&q[4]);
c.cx(&q[3],&q[5]);
c.cx(&q[4],&q[0]);
c.cx(&q[4],&q[1]);
c.cx(&q[4],&q[2]);
c.cx(&q[4],&q[3]);
c.cx(&q[4],&q[5]);
c.cx(&q[5],&q[0]);
c.cx(&q[5],&q[1]);
c.cx(&q[5],&q[2]);
c.cx(&q[5],&q[3]);
c.cx(&q[5],&q[4]);
c.cx(&q[1],&q[0]);
c.cx(&q[2],&q[0]);
c.x(&q[0]);
}
pub fn run(){
 use crate::sim::Simulator;use sha3::digest::XofReader;
 struct Fixed;impl XofReader for Fixed{fn read(&mut self,b:&mut[u8]){b.fill(0x39)}}
 let mut c=Circuit::new();let q=c.alloc_qreg_bits("six-data-three-existing-dirty",9);let n=c.b.next_qubit;coordinate(&mut c,&q);assert_eq!(n,c.b.next_qubit);let ops=c.into_builder().ops;
 for o in &ops{o.validate();assert!(matches!(o.kind,K::X|K::CX|K::CCX));}
 let mut outputs=Vec::new();for batch in 0..8{let before:Vec<u64>=(0..9).map(|bit|(0..64).fold(0,|v,l|v|((((64*batch+l)>>bit&1)as u64)<<l))).collect();let mut f=Fixed;let mut sim=Simulator::new(9,0,&mut f);sim.qubits.copy_from_slice(&before);sim.apply_iter(ops.iter());
  for l in 0..64{let x=64*batch+l;let y=(0..9).fold(0,|v,i|v|(((sim.qubits[i]>>l&1)as usize)<<i));assert_eq!(y>>6,x>>6);let z=x&63;assert_eq!(y&1,usize::from((z&3)+(z>>2&3)+(z>>4&3)>=5));if batch==0{outputs.push(y);}else{assert_eq!(y&63,outputs[l]);}}
  assert_eq!(sim.phase,0);sim.apply_iter(ops.iter().rev());assert_eq!(sim.qubits,before);assert_eq!(sim.phase,0);
 }
 let mut sorted=outputs.clone();sorted.sort_unstable();assert_eq!(sorted,(0..64).collect::<Vec<_>>());assert_eq!(ops.iter().filter(|o|o.kind==K::CCX).count(),15);
 eprintln!("SIDE_COORDINATE_NATIVE_PASS lanes=512 T=15 ops={} data=6 dirty_restored=3 extra_allocated=0 permutation=true inverse=true phase=0 wholeQ792=false",ops.len());
}
pub fn budget(){
 std::env::set_var("Q792_MEMORY_BUDGET","1");let(mut total_t,mut unfold_t,mut spans)=(0u64,0u64,0u64);let mut stages=std::collections::BTreeMap::<&'static str,u64>::new();
 for block in 0..202{for j in 0..4{
  PATTERNS.with(|p|p.borrow_mut().clear());STAGES.with(|p|p.borrow_mut().clear());let ops=super::q792_lifecycle_r01::template(block,j);
  let mut patterns=PATTERNS.with(|p|p.borrow_mut().drain(..).collect::<Vec<_>>());let backward=patterns.iter().map(|p|p.iter().rev().cloned().collect::<Vec<_>>()).collect::<Vec<_>>();patterns.extend(backward);
  let mut seen=std::collections::HashSet::new();patterns.retain(|p|seen.insert(p.iter().map(signature).collect::<Vec<_>>()));patterns.sort_by_key(|p|std::cmp::Reverse(p.len()));
  let mut first=std::collections::HashMap::new();for (id,p) in patterns.iter().enumerate(){first.entry(signature(&p[0])).or_insert_with(Vec::new).push(id);}
  let(mut at,mut hit_t,mut hit_n)=(0usize,0u64,0u64);
  while at<ops.len(){let found=first.get(&signature(&ops[at])).and_then(|ids|ids.iter().find_map(|&id|{let p=&patterns[id];(at+p.len()<=ops.len()&&ops[at..at+p.len()].iter().zip(p).all(|(a,b)|signature(a)==signature(b))).then_some(id)}));if let Some(id)=found{let p=&patterns[id];hit_t+=p.iter().filter(|o|o.kind==K::CCX).count()as u64;hit_n+=1;at+=p.len();}else{at+=1;}}
  let t=ops.iter().filter(|o|o.kind==K::CCX).count()as u64;total_t+=2*t;unfold_t+=2*hit_t;spans+=2*hit_n;
  STAGES.with(|s|{for &(name,_,t) in s.borrow().iter(){*stages.entry(name).or_default()+=2*t;}});
  eprintln!("MEMORY_BUDGET_TEMPLATE block={block} j={j} T={t} unfold_T={hit_t} unfold_spans={hit_n} patterns={}",patterns.len());
 }}
 for (name,t) in stages{eprintln!("MEMORY_BUDGET_STAGE_PREOPT name={name} traversal_T={t} four_traversal_T={}",4*t);}
 eprintln!("MEMORY_BUDGET_PASS templates=808 traversal_T={total_t} matched_unfold_T={unfold_t} matched_spans={spans} four_traversal_T={} four_unfold_T={} note=matched_exact_full_sequences_not_global_upper_bound_if_unmatched_transformed_fragments",4*total_t,4*unfold_t);
}
