//! T-only H: V^-1 C W^-1 Q W C^-1 V, after literal inverse-pair cancellation.
//! Source lowA plus known 2^A; source[A:A+2] is arbitrary packed cargo.
//! Supplied upper is A; mask/carry zero only on g. No allocation or mode bit.
use crate::point_add::trailmix_port::circuit::{Circuit,QReg};
fn dirty(c:&mut Circuit,cs:&[&QReg],out:&QReg,d:&[QReg]){match cs.len(){0=>c.x(out),1=>c.cx(cs[0],out),2=>c.ccx(cs[0],cs[1],out),n=>{assert!(d.len()>=n-2);let ds=&d[..n-2];for seed in[true,false]{if seed{c.ccx(cs[0],cs[1],&ds[0]);}for i in 1..ds.len(){c.ccx(&ds[i-1],cs[i+1],&ds[i]);}c.ccx(ds.last().unwrap(),cs[n-1],out);for i in(1..ds.len()).rev(){c.ccx(&ds[i-1],cs[i+1],&ds[i]);}if seed{c.ccx(cs[0],cs[1],&ds[0]);}}}}}
fn swap(c:&mut Circuit,g:&QReg,a:&QReg,b:&QReg){c.cx(b,a);c.ccx(g,a,b);c.cx(b,a);}
struct E<'a>{x:&'a[QReg],y:&'a[QReg],upper:&'a[QReg],q:&'a QReg,g:&'a QReg,mask:&'a QReg,carry:&'a QReg,d:&'a[QReg]}
impl E<'_>{
 fn range(&self,c:&mut Circuit,i:usize){if i==0{c.cx(self.g,self.mask);}let cs:Vec<_>=self.upper.iter().enumerate().map(|(b,q)|(q,i>>b&1!=0)).collect();c.x(self.g);super::paired_clean_mcx::toggle(c,&cs,self.mask,self.g);c.x(self.g);}
 fn tail(&self,c:&mut Circuit){for i in(0..self.x.len()).rev(){c.x(self.g);super::paired_clean_mcx::toggle(c,&[(self.mask,true),(&self.y[i],true),(&self.x[i],true)],self.carry,self.g);c.x(self.g);c.cx(self.carry,&self.x[i]);c.cx(&self.x[i],&self.y[i]);c.cx(self.carry,&self.x[i]);dirty(c,&[self.g,self.mask,&self.x[i],self.q],&self.y[i],self.d);c.cx(self.carry,&self.x[i]);let at=c.b.ops.len();self.range(c,i);c.b.ops[at..].reverse();}}
 fn gather<'b>(&self,c:&mut Circuit,w:&'b[QReg],p:usize)->&'b QReg{let mut nodes:Vec<_>=w.iter().skip(p).step_by(2).collect();for b in 1..self.upper.len(){let mut next=Vec::new();for pair in nodes.chunks_exact(2){swap(c,&self.upper[b],pair[0],pair[1]);next.push(pair[0]);}nodes=next;}nodes[0]}
 fn prep<'b>(&'b self,c:&mut Circuit)->(&'b QReg,&'b QReg){let s1=self.gather(c,self.x,1);let t1=self.gather(c,self.y,1);let at=c.b.ops.len();for i in(1..self.upper.len()).rev(){dirty(c,&self.upper[..i].iter().collect::<Vec<_>>(),&self.upper[i],self.d);}let inc=c.b.ops[at..].to_vec();let s0=self.gather(c,self.x,0);let t0=self.gather(c,self.y,0);c.b.ops.extend(inc.into_iter().rev());swap(c,&self.upper[0],s0,s1);swap(c,&self.upper[0],t0,t1);c.cx(s0,t0);c.cx(s1,t1);(t0,t1)}
 fn w(&self,c:&mut Circuit,t0:&QReg,t1:&QReg){dirty(c,&[self.g,self.q,self.carry],t1,self.d);c.x(self.carry);c.x(t0);dirty(c,&[self.g,self.q,self.carry,t0],t1,self.d);c.x(t0);dirty(c,&[self.g,self.q,self.carry],t0,self.d);c.x(self.carry);}
 fn compare(&self,c:&mut Circuit,t0:&QReg,t1:&QReg){c.cx(self.g,self.q);dirty(c,&[self.g,self.carry,t1],self.q,self.d);c.x(self.carry);c.x(t0);c.x(t1);dirty(c,&[self.g,self.carry,t0,t1],self.q,self.d);c.x(t1);c.x(t0);c.x(self.carry);}
}
pub(super)fn emit(c:&mut Circuit,x:&[QReg],y:&[QReg],upper:&[QReg],q:&QReg,g:&QReg,mask:&QReg,carry:&QReg,d:&[QReg]){assert_eq!(x.len(),1<<upper.len());assert_eq!(x.len(),y.len());assert!(upper.len()>=2&&d.len()>=18);let owned=c.b.next_qubit;let e=E{x,y,upper,q,g,mask,carry,d};let at=c.b.ops.len();e.tail(c);let v=c.b.ops[at..].to_vec();c.b.ops[at..].reverse();let at=c.b.ops.len();let(t0,t1)=e.prep(c);let cp=c.b.ops[at..].to_vec();let at=c.b.ops.len();e.w(c,t0,t1);let w=c.b.ops[at..].to_vec();c.b.ops[at..].reverse();e.compare(c,t0,t1);c.b.ops.extend(w);c.b.ops.extend(cp.into_iter().rev());c.b.ops.extend(v);assert_eq!(c.b.next_qubit,owned);}
pub fn run(){use crate::{circuit::OperationType as K,sim::Simulator};use sha3::digest::XofReader;use std::io::Write;struct Fixed;impl XofReader for Fixed{fn read(&mut self,b:&mut[u8]){b.fill(0x69)}}let root=std::path::PathBuf::from(std::env::var_os("Q792_T_ONLY_H_DIR").expect("Q792_T_ONLY_H_DIR"));let mut total=0;for h in[3,6,8]{let n=1<<h;let nw=2*n+h+22;let nb=(nw+7)/8;let mut c=Circuit::new();c.b.count_only=false;c.b.fiat_hash=None;let qs=c.alloc_qreg_bits("T-only-H",nw);let q=2*n+h;emit(&mut c,&qs[..n],&qs[n..2*n],&qs[2*n..q],&qs[q],&qs[q+1],&qs[q+2],&qs[q+3],&qs[q+4..]);assert_eq!(c.b.next_qubit as usize,nw);let ops=c.into_builder().ops;for op in &ops{op.validate();assert!(matches!(op.kind,K::X|K::CX|K::CCX));}let mut out=std::fs::File::create(root.join(format!("t-only-h{h}-native-ops.bin"))).unwrap();for op in&ops{let k=match op.kind{K::X=>0u32,K::CX=>1,K::CCX=>2,_=>unreachable!()};for v in[k,op.q_target.0 as u32,op.q_control1.0 as u32,op.q_control2.0 as u32]{out.write_all(&v.to_le_bytes()).unwrap();}}let data=std::fs::read(root.join(format!("t-only-h{h}-cases.bin"))).unwrap();assert_eq!(data.len()%(2*nb*64),0);for(batch,records)in data.chunks_exact(2*nb*64).enumerate(){let mut before=vec![0u64;nw];let mut after=before.clone();for(lane,row)in records.chunks_exact(2*nb).enumerate(){for i in 0..nw{before[i]|=u64::from(row[i/8]>>(i%8)&1)<<lane;after[i]|=u64::from(row[nb+i/8]>>(i%8)&1)<<lane;}}let mut fixed=Fixed;let mut sim=Simulator::new(nw,0,&mut fixed);sim.qubits.copy_from_slice(&before);sim.apply_iter(ops.iter());assert_eq!(sim.qubits,after,"T-only h={h} batch={batch}");assert_eq!(sim.phase,0);sim.apply_iter(ops.iter().rev());assert_eq!(sim.qubits,before,"T-only inverse h={h} batch={batch}");assert_eq!(sim.phase,0);total+=64;}eprintln!("T_ONLY_H_BODY_NATIVE_PASS h={h} T={} N={} cases={} inverse=true phase=0 allocation=0",ops.iter().filter(|o|o.kind==K::CCX).count(),ops.len(),data.len()/(2*nb));}eprintln!("T_ONLY_H_BODY_ALL_PASS cases={total} whole_candidate=false");}
