//! Exact arbitrary-state distributivity across proved commuting intervals.
//! t^=a*b; t^=a*c becomes b^=c; t^=a*b; b^=c. All controls restored.
//! Also u^=a*b;v^=a*b becomes v^=u;u^=a*b;v^=u, using arbitrary old u.
use crate::circuit::{Op,OperationType as K,QubitId,NO_QUBIT,NO_BIT};
pub(super) fn apply(ops:&mut Vec<Op>)->(usize,usize){
 let n=ops.iter().flat_map(|o|[o.q_target,o.q_control1,o.q_control2]).filter(|q|*q!=NO_QUBIT).map(|q|q.0 as usize+1).max().unwrap_or(0);
 let old_t=ops.iter().filter(|o|o.kind==K::CCX).count();let old_n=ops.len();let mut out:Vec<Option<Op>>=Vec::with_capacity(old_n);let mut same=vec![Vec::<usize>::new();n];let mut writes=vec![None::<usize>;n];let mut reads=vec![None::<usize>;n];let mut saved=0;let mut predicates=std::collections::HashMap::<(usize,usize),Vec<usize>>::new();
 fn push(o:Op,out:&mut Vec<Option<Op>>,writes:&mut[Option<usize>],reads:&mut[Option<usize>]){o.validate();let id=out.len();writes[o.q_target.0 as usize]=Some(id);for q in [o.q_control1,o.q_control2]{if q!=NO_QUBIT{reads[q.0 as usize]=Some(id);}}out.push(Some(o));}
 fn gate(k:K,t:usize,a:usize,b:usize)->Op{let mut o=Op::empty();o.kind=k;o.q_target=QubitId(t as u64);o.q_control1=QubitId(a as u64);if k==K::CCX{o.q_control2=QubitId(b as u64);}o}
 for &o in ops.iter(){assert!(matches!(o.kind,K::X|K::CX|K::CCX)&&o.c_condition==NO_BIT&&o.c_target==NO_BIT);let t=o.q_target.0 as usize;let mut pair=None;
  if o.kind==K::CCX{let mut cs=[o.q_control1.0 as usize,o.q_control2.0 as usize];cs.sort_unstable();let key=(cs[0],cs[1]);let found=predicates.get(&key).and_then(|ids|ids.iter().rev().take(32).find_map(|&p|{let v=out[p]?;let old=v.q_target.0 as usize;if old==t||reads[old].is_some_and(|r|r>=p)||cs.iter().any(|&q|writes[q].is_some_and(|w|w>=p)){None}else{Some((p,old))}}));if let Some((p,old))=found{out[p]=None;push(gate(K::CX,t,old,0),&mut out,&mut writes,&mut reads);push(gate(K::CCX,old,cs[0],cs[1]),&mut out,&mut writes,&mut reads);push(gate(K::CX,t,old,0),&mut out,&mut writes,&mut reads);saved+=1;continue;}}
  if o.kind==K::CCX{let controls=[o.q_control1.0 as usize,o.q_control2.0 as usize];for &p in same[t].iter().rev().take(32){let Some(v)=out[p]else{continue;};if reads[t].is_some_and(|r|r>=p){break;}let prev=[v.q_control1.0 as usize,v.q_control2.0 as usize];if prev.iter().any(|&q|writes[q].is_some_and(|w|w>=p)){continue;}for a in prev{if let Some(pos)=controls.iter().position(|&q|q==a){let b=*prev.iter().find(|&&q|q!=a).unwrap();let c=controls[1-pos];if b!=c{pair=Some((p,a,b,c));break;}}}if pair.is_some(){break;}}}
  if let Some((p,a,b,c))=pair{out[p]=None;push(gate(K::CX,b,c,0),&mut out,&mut writes,&mut reads);push(gate(K::CCX,t,a,b),&mut out,&mut writes,&mut reads);push(gate(K::CX,b,c,0),&mut out,&mut writes,&mut reads);saved+=1;}else{let ix=out.len();push(o,&mut out,&mut writes,&mut reads);if o.kind==K::CCX{same[t].push(ix);let mut cs=[o.q_control1.0 as usize,o.q_control2.0 as usize];cs.sort_unstable();predicates.entry((cs[0],cs[1])).or_default().push(ix);}}
 }
 let candidate:Vec<_>=out.into_iter().flatten().collect();assert_eq!(candidate.iter().filter(|o|o.kind==K::CCX).count()+saved,old_t);assert_eq!(candidate.len(),old_n+saved);*ops=candidate;(saved,old_n)
}
pub fn check(){use sha3::digest::XofReader;use crate::sim::Simulator;struct F;impl XofReader for F{fn read(&mut self,b:&mut[u8]){b.fill(0x79)}}let mut seed=0x79257a20260913u64;let mut saved=0;for case in 0..2048{let mut ops=Vec::new();for _ in 0..32+case%64{seed^=seed<<13;seed^=seed>>7;seed^=seed<<17;let a=seed as usize%8;let b=(a+1+(seed>>8)as usize%7)%8;let mut t=(b+1+(seed>>16)as usize%7)%8;if t==a{t=(t+1)%8;if t==b{t=(t+1)%8;}}let mut o=Op::empty();o.kind=[K::X,K::CX,K::CCX][(seed>>24)as usize%3];o.q_target=QubitId(t as u64);if o.kind!=K::X{o.q_control1=QubitId(a as u64);}if o.kind==K::CCX{o.q_control2=QubitId(b as u64);}o.validate();ops.push(o);}let mut candidate=ops.clone();saved+=apply(&mut candidate).0;for base in [0,64,128,192]{let before:Vec<_>=(0..8).map(|bit|(0..64).fold(0u64,|v,l|v|((((base+l)>>bit)&1)as u64)<<l)).collect();let mut fa=F;let mut fb=F;let mut a=Simulator::new(8,0,&mut fa);let mut b=Simulator::new(8,0,&mut fb);a.qubits.copy_from_slice(&before);b.qubits.copy_from_slice(&before);a.apply_iter(ops.iter());b.apply_iter(candidate.iter());assert_eq!(a.qubits,b.qubits,"star factor case={case}");assert_eq!(a.phase,b.phase);b.apply_iter(candidate.iter().rev());assert_eq!(b.qubits,before);}}assert!(saved>0);eprintln!("STAR_FACTOR_NATIVE_PASS programs=2048 exhaustive_cases=524288 phase=0 inverse=true saved_T={saved}");}
