use super::*;use crate::sim::Simulator;use sha3::digest::XofReader;
struct Rng(Vec<u8>,usize);impl XofReader for Rng{fn read(&mut self,b:&mut[u8]){b.fill(self.0[self.1.min(self.0.len()-1)]);self.1+=1;}}
fn two_t(s:&State,n:usize)->isize{let raw=s.output_hist[OperationType::CCX as usize]+s.output_hist[OperationType::CCZ as usize]-s.outer_lowered;2*raw as isize-(2*n*s.predicate_blocks-s.carry_selected-s.endpoint_blocks-s.endpoint_outer)as isize}
#[test]fn combined_boundaries_full_phase_accounting_and_n1_overlap(){
 let mut cases=0;for n in [1,2,3,4,256]{for shifted in [false,true]{
 let data=endpoint_tests::fixture(n);let build=|enabled,retain|{let inputs:Vec<_>=(0..513).chain([514,515]).collect();let mut s=State::new(518,256,&inputs,&[0],retain,0);s.endpoint_enabled=enabled;s.carry_enabled=enabled;if shifted{s.qmap[0]=QubitId(515);}s.raw(OperationType::PushCondition).c_condition=BitId(0);let mut r=Reader{data:&data,at:0};predicate_cleanup_n(&mut r,&mut s,2267,0,0,n);s.raw(OperationType::PopCondition);for _ in 0..2{let o=s.raw(OperationType::CCX);o.q_control1=QubitId(1);o.q_control2=QubitId(2);o.q_target=QubitId(516);}s.flush_raw();s.assert_accounting(8*n+5+4,0);s};
 let old=build(false,true);let new=build(true,true);let count=build(true,false);let lsb=usize::from(n>1);assert_eq!(new.carry_selected,lsb);assert_eq!(new.endpoint_blocks,1);assert_eq!(new.endpoint_outer,usize::from(!shifted));assert_eq!(new.selected_delta,5*lsb as isize-2);assert_eq!(new.trace,old.trace);assert_eq!(new.proof.diagnostic_fingerprint(),old.proof.diagnostic_fingerprint());assert_eq!(new.output_hist,count.output_hist);assert_eq!(new.final_private_hmr,count.final_private_hmr);assert_eq!(new.final_private_neg,count.final_private_neg);assert!(new.capture.is_none());assert_eq!(two_t(&old,n)-two_t(&new,n),(lsb+1+usize::from(!shifted))as isize);
 let samples=if n<=4{1usize<<(2*n)}else{64};for mask in 0..samples{for ctrl in 0..2u64{for active in 0..2u64{for pred in [0,255]{for local in [0,255]{for next in [0,255]{for stale in 0..2u64{
  let mut ra=Rng(vec![pred,next],0);let mut rb=Rng(if lsb==1{vec![pred,local,next]}else{vec![pred,next]},0);let mut a=Simulator::new(518,258,&mut ra);let mut b=Simulator::new(518,258,&mut rb);a.qubits[if shifted{515}else{0}]=ctrl;for j in 0..n{a.qubits[257+j]=if n<=4{((mask>>j)&1)as u64}else{(mask as u64).rotate_left((j%64)as u32)&1};a.qubits[1+j]=if n<=4{((mask>>(n+j))&1)as u64}else{(mask as u64).rotate_right((j%64)as u32)&1};}a.qubits[514]=mask as u64&1;a.bits[0]=active;a.bits[256]=stale;a.bits[257]=stale;b.qubits=a.qubits.clone();b.bits=a.bits.clone();a.apply_iter(old.out.iter());b.apply_iter(new.out.iter());assert_eq!(a.qubits,b.qubits);assert_eq!(a.phase,b.phase);assert_eq!(a.bits,b.bits);cases+=1;
 }}}}}}}
 }}assert_eq!(cases,51712);
}
#[test]fn existing_inner_capture_declines_both_without_overwrite(){let data=endpoint_tests::fixture(2);let mut s=State::new(518,256,&(0..513).collect::<Vec<_>>(),&[],false,0);s.endpoint_enabled=true;s.carry_enabled=true;s.capture=Some(Vec::new());let mut r=Reader{data:&data,at:0};predicate_cleanup_n(&mut r,&mut s,2267,0,0,2);s.flush_raw();assert_eq!(s.endpoint_blocks,0);assert_eq!(s.carry_selected,0);assert_eq!(s.capture.as_ref().unwrap().len(),s.output_ops);}
#[test]fn dirty_carry_keeps_endpoint_but_declines_lsb(){let data=endpoint_tests::fixture(2);let build=|enabled|{let mut s=State::new(518,256,&(0..515).collect::<Vec<_>>(),&[],true,0);s.endpoint_enabled=enabled;s.carry_enabled=enabled;let mut r=Reader{data:&data,at:0};predicate_cleanup_n(&mut r,&mut s,2267,0,0,2);s.flush_raw();s};let old=build(false);let new=build(true);assert_eq!(new.endpoint_blocks,1);assert_eq!(new.carry_selected,0);assert_eq!(new.trace,old.trace);for mask in 0..64u64{for m in [0,255]{let mut ra=Rng(vec![m],0);let mut rb=Rng(vec![m],0);let mut a=Simulator::new(518,258,&mut ra);let mut b=Simulator::new(518,258,&mut rb);for(j,q)in [0,1,2,257,258,514].into_iter().enumerate(){a.qubits[q]=(mask>>j)&1;}a.qubits[513]=1;b.qubits=a.qubits.clone();a.apply_iter(old.out.iter());b.apply_iter(new.out.iter());assert_eq!(a.qubits,b.qubits);assert_eq!(a.phase,b.phase);assert_eq!(a.bits,b.bits);}}}
#[test]fn both_refinements_deliver_once_to_existing_outer_buffer(){let data=endpoint_tests::fixture(2);for retain in [false,true]{let mut s=State::new(518,256,&(0..513).collect::<Vec<_>>(),&[],retain,0);s.endpoint_enabled=true;s.carry_enabled=true;s.comparator_capture=Some(Vec::new());let mut r=Reader{data:&data,at:0};predicate_cleanup_n(&mut r,&mut s,2267,0,0,2);s.flush_raw();assert_eq!(s.carry_selected,1);assert_eq!(s.endpoint_blocks,1);assert_eq!(s.final_private_hmr,0);assert_eq!(s.final_private_neg,0);let v=s.comparator_capture.take().unwrap();assert_eq!(v.len(),s.output_ops);for o in v{s.deliver(o);}s.assert_accounting(21,0);assert_eq!(s.final_private_hmr,1);assert_eq!(s.final_private_neg,1);}}
