fn tests(){use super::{OperationType as K,Op,BitId};use crate::sim::Simulator;use sha3::digest::XofReader;struct R(u64,usize);impl XofReader for R{fn read(&mut self,b:&mut[u8]){assert!(self.1<8);b.fill(if self.0>>self.1&1==1{255}else{0});self.1+=1;}}
let data=include_bytes!("family24_fixture.hir").as_slice();let mut r=Reader{data,at:0};let v:Vec<_>=(0..5).map(|_|read(&mut r)).collect();let b=v[2].q[0];let a=if v[0].q[0]==b{v[0].q[1]}else{v[0].q[0]};let t=v[0].q[2];let c=if v[1].q[0]==b{v[1].q[1]}else{v[1].q[0]};let d=v[1].q[2];let locals=[a,b,t,c,d];let mut selected=0;let mut fall=0;let mut cases=0;let mut saw_one=false;let mut saw_zero=false;
for known in 0..34{for condition in 0..4{
 let inputs:Vec<_>=(1..=5).filter(|j|if known<32{known>>(j-1)&1==0}else{*j!=5}).collect();
 let build=|enable,retain|{let mut s=State::new(7,1,&inputs,&[0],retain,0);s.comparator_capture=Some(Vec::new());s.family24_locations=vec![vec![0]];s.qmap=vec![QubitId(0);580];for(j,&q)in locals.iter().enumerate(){s.qmap[q]=QubitId(j as u64+1);}
 if known>=32{if known==33{s.raw(K::X).q_target=QubitId(5);}let o=s.raw(K::CCX);o.q_control1=QubitId(2);o.q_control2=QubitId(4);o.q_target=QubitId(5);}
 if condition>0{if condition<3{let o=s.raw(if condition==1{K::BitStore1}else{K::BitStore0});o.c_target=BitId(0);}s.raw(K::PushCondition).c_condition=BitId(0);}
 if enable{let mut rr=Reader{data,at:0};assert_eq!(try_apply(&mut s,&mut rr,0,0,5,0,580,usize::MAX),Some(5));assert_eq!(rr.at,data.len());}else{for o in &v{let mut q=[NO_QUBIT;3];for j in 0..o.nq{q[j]=s.qmap[o.q[j]];}s.emit_leaf(o.t,&q,o.nq,NO_BIT,0);}}
 if condition>0{s.raw(K::PopCondition);}let o=s.raw(K::CCX);o.q_control1=QubitId(1);o.q_control2=QubitId(2);o.q_target=QubitId(6);let o=s.raw(K::CCX);o.q_control1=QubitId(1);o.q_control2=QubitId(2);o.q_target=QubitId(6);s.flush_raw();let outer=s.comparator_capture.take().unwrap();assert_eq!(outer.len(),s.output_ops);for op in outer{s.deliver(op);}s.assert_accounting(s.input_ops,0);assert!(s.proof.balanced());s};
 let got=build(true,true);let counted=build(true,false);let old=build(false,true);assert_eq!(got.input_hist,old.input_hist);assert_eq!(got.trace,old.trace);assert_eq!(got.proof.diagnostic_fingerprint(),old.proof.diagnostic_fingerprint());assert_eq!(got.output_hist,counted.output_hist);assert_eq!(got.selected_delta,counted.selected_delta);assert_eq!(got.one_cleanups,counted.one_cleanups);assert_eq!(got.skipped_one,counted.skipped_one);assert_eq!(got.skipped_cleanups,counted.skipped_cleanups);assert_eq!(got.proof.rewrites,old.proof.rewrites);assert_eq!(got.family24_counts,counted.family24_counts);assert!(counted.out.is_empty());if got.family24_counts[1]>0{selected+=1;assert_eq!(got.skipped_cleanups,0);assert_eq!(got.skipped_one,0);}else{fall+=1;assert_eq!(got.output_hist,old.output_hist);}saw_one|=old.one_cleanups>0;saw_zero|=old.proof.rewrites>0;
 let nh=old.out.iter().filter(|o|matches!(o.kind,K::Hmr|K::R)).count();assert!(nh<=8);
 for mask in 0..32u64{if (1..=5).any(|j|!inputs.contains(&j)&&mask>>(j-1)&1!=0){continue;}for active in 0..2{for outcome in 0..(1u64<<nh){for stale in [0,1]{let mut r1=R(outcome,0);let mut r2=R(outcome,0);let mut want=Simulator::new(7,3,&mut r1);let mut have=Simulator::new(7,3,&mut r2);for j in 0..5{want.qubits[j+1]=mask>>j&1;have.qubits[j+1]=want.qubits[j+1];}want.bits[0]=active;have.bits[0]=active;want.bits[1]=stale;have.bits[1]=stale;want.apply_iter(old.out.iter());have.apply_iter(got.out.iter());assert_eq!(want.qubits,have.qubits);assert_eq!(want.phase,have.phase);assert_eq!(want.bits,have.bits);cases+=1;}}}}
}}
// Every pairwise physical alias and every q0 mapping must reject before mutation.
for i in 0..5{for j in i+1..5{let mut s=State::new(7,1,&[1,2,3,4,5],&[],true,0);s.family24_locations=vec![vec![0]];s.qmap=vec![QubitId(0);580];for(k,&q)in locals.iter().enumerate(){s.qmap[q]=QubitId(k as u64+1);}s.qmap[locals[j]]=s.qmap[locals[i]];let mut r=Reader{data,at:0};assert_eq!(try_apply(&mut s,&mut r,0,0,5,0,580,usize::MAX),None);assert_eq!(s.input_ops,0);}}
for i in 0..5{let mut s=State::new(7,1,&[],&[],true,0);s.family24_locations=vec![vec![0]];s.qmap=vec![QubitId(0);580];for(k,&q)in locals.iter().enumerate(){s.qmap[q]=QubitId(k as u64+1);}s.qmap[locals[i]]=QubitId(0);let mut r=Reader{data,at:0};assert_eq!(try_apply(&mut s,&mut r,0,0,5,0,580,usize::MAX),None);assert_eq!(s.input_ops,0);}
for kind in 0..3{let mut s=State::new(7,1,&[],&[],true,0);s.family24_locations=vec![if kind==0{vec![]}else{vec![0]}];s.qmap=vec![QubitId(0);580];for(k,&q)in locals.iter().enumerate(){s.qmap[q]=QubitId(k as u64+1);}let mut bad=data.to_vec();if kind==2{bad[1]=1;bad.insert(3,0);}let mut r=Reader{data:&bad,at:0};assert_eq!(try_apply(&mut s,&mut r,0,0,5,0,580,if kind==1{0}else{usize::MAX}),None);assert_eq!(s.input_ops,0);assert_eq!(r.at,0);}
assert!(selected>0&&fall>0&&saw_one&&saw_zero);println!("PASS cases={cases} selected_contexts={selected} fallback_contexts={fall};32 input-known patterns+zero/one correlated products,4condition contexts,all10aliases/all5q0 rejects,actualSimulator phase/private overwrite,retained/count histogram+trace+Proof parity,one/oldcleanup accounting");}
