//! Emitted-op selftest of `ring_rotate` on the 64-shot bitsliced `Simulator`
//! (the `retained_division.rs` / `midq_gate_compare_selftest` pattern): build a
//! small circuit, load values, apply `c.b.ops`, read the registers back.
//!
//! Checks, for every case: forward output = cyclic left rotation by
//! `amount mod W`; inverse output = cyclic right rotation; inverse applied to
//! the forward output restores the input exactly (same data, same amount);
//! `amount` unchanged; phase 0; every wire outside ring + amount (there are
//! none allocated, so all of `sim.qubits` beyond the loaded ids) zero.
//!
//! Coverage: exhaustive permutation check (every amount in `[0, 2^k)`, every
//! one-hot input, plus dense pseudo-random inputs) on widths 2, 4, 7, 8, 16, 33;
//! on width 257 the one-hot permutation check for every amount in `[0, 128)`
//! (k = 7: every single layer and every layer combination), dense random
//! inputs with amounts below 128, and an 8-bit-amount random check (amounts
//! below 256). Toffoli counts are asserted against `layer_toffoli` and the
//! design's `k (W - 1)` bound and printed per layer.
//!
//! Adversarial review additions (`run_review`, 2026-09-13; see the block at
//! the end of the file): the ring as a sub-slice of full 257-wire registers
//! with foreign neighbours at wires L-1 and T; every amount in `[0, 2^k)` on
//! widths 256/255/128 (k = 8) and 64 (k = 7) and the upper half of the 8-bit
//! amounts on 257, a 9-bit amount on 257; 40 real PZ rows generated by
//! `tools/packed_prefix_model.py` in the refuters' classes (R1 gap 0, e_A =
//! W_A with off 0/1, the late-row attainer whose merged amount equals the ring
//! width, first multiply with ca_old = 0 and e_B in [226, 256] and with
//! e_B <= 225, draining, terminal, d >= 15, gap >= 15, tight multiply,
//! mid-step rings) run through the design's D3/D5/D11/D10 and M1/M3/M9/M11
//! rotation sequences with the design's placement claims asserted; the
//! reversed-slice (bit-order) convention; inverse-first round trips; an
//! op-kind audit (CX/CCX only, #CX = 2 #CCX). Whole file: ~0.8 s.

use super::{layer_toffoli, ring_rotate, toffoli};
use crate::circuit::{analyze_ops, Op, OperationType, QubitId};
use crate::point_add::trailmix_port::circuit::{Circuit, QReg};
use crate::sim::Simulator;
use sha3::{
    digest::{ExtendableOutput, Update},
    Shake256,
};

fn ids(reg: &[QReg]) -> Vec<QubitId> {
    reg.iter().map(|q| QubitId(q.id().into())).collect()
}

fn tof(ops: &[Op]) -> usize {
    ops.iter()
        .filter(|op| matches!(op.kind, OperationType::CCX | OperationType::CCZ))
        .count()
}

/// xorshift64* for the dense inputs (deterministic, no crate).
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }

    fn bits(&mut self, n: usize) -> Vec<bool> {
        (0..n).map(|_| self.next() >> 63 == 1).collect()
    }
}

struct Harness {
    forward: Vec<Op>,
    inverse: Vec<Op>,
    ring: Vec<QubitId>,
    amount: Vec<QubitId>,
    nq: usize,
    w: usize,
    k: usize,
}

impl Harness {
    fn build(w: usize, k: usize) -> Self {
        let circuits: Vec<(Vec<Op>, Vec<QubitId>, Vec<QubitId>, usize)> = [false, true]
            .iter()
            .map(|&inverse| {
                let mut c = Circuit::new();
                let ring = c.alloc_qreg_bits("ring", w);
                let amount = c.alloc_qreg_bits("amount", k);
                ring_rotate(&mut c, &ring, &amount, inverse);
                let (nq, _, _, _) = analyze_ops(c.b.ops.iter());
                (c.b.ops.clone(), ids(&ring), ids(&amount), nq as usize)
            })
            .collect();
        assert_eq!(circuits[0].1, circuits[1].1);
        assert_eq!(circuits[0].2, circuits[1].2);
        let nq = circuits[0].3.max(circuits[1].3).max(w + k);
        Self {
            forward: circuits[0].0.clone(),
            inverse: circuits[1].0.clone(),
            ring: circuits[0].1.clone(),
            amount: circuits[0].2.clone(),
            nq,
            w,
            k,
        }
    }

    /// Apply `ops` to up to 64 (value, amount) cases at once; returns the ring
    /// values read back. Asserts phase 0, amount unchanged, scratch clean.
    fn run(&self, ops: &[Op], cases: &[(Vec<bool>, usize)], what: &str) -> Vec<Vec<bool>> {
        assert!(!cases.is_empty() && cases.len() <= 64);
        let mask = if cases.len() == 64 { u64::MAX } else { (1u64 << cases.len()) - 1 };
        let mut seed = Shake256::default();
        seed.update(b"packed-ring-rotate-selftest-v1");
        seed.update(&(self.w as u64).to_le_bytes());
        let mut xof = seed.finalize_xof();
        let mut sim = Simulator::new(self.nq, 1, &mut xof);
        for (shot, (value, amount)) in cases.iter().enumerate() {
            assert_eq!(value.len(), self.w);
            for (w, &bit) in value.iter().enumerate() {
                if bit {
                    *sim.qubit_mut(self.ring[w]) |= 1u64 << shot;
                }
            }
            for (i, &id) in self.amount.iter().enumerate() {
                if (amount >> i) & 1 == 1 {
                    *sim.qubit_mut(id) |= 1u64 << shot;
                }
            }
        }
        sim.apply_iter(ops.iter());
        assert_eq!(sim.phase & mask, 0, "{what}: phase garbage (W={}, k={})", self.w, self.k);
        let mut out = Vec::with_capacity(cases.len());
        for (shot, (_, amount)) in cases.iter().enumerate() {
            for (i, &id) in self.amount.iter().enumerate() {
                assert_eq!(
                    (sim.qubit(id) >> shot) & 1,
                    ((amount >> i) & 1) as u64,
                    "{what}: amount wire {i} changed (W={}, amount={amount})",
                    self.w
                );
            }
            out.push(
                self.ring
                    .iter()
                    .map(|&id| (sim.qubit(id) >> shot) & 1 == 1)
                    .collect::<Vec<bool>>(),
            );
        }
        for &id in self.ring.iter().chain(&self.amount) {
            *sim.qubit_mut(id) = 0;
        }
        assert!(
            sim.qubits.iter().all(|&q| q & mask == 0),
            "{what}: dirty scratch (W={}, k={})",
            self.w,
            self.k
        );
        out
    }

    /// Forward, inverse-of-forward (round trip on the same data) and inverse
    /// alone on every case; returns the number of cases checked.
    fn check(&self, cases: &[(Vec<bool>, usize)]) -> usize {
        let w = self.w;
        let rotl = |v: &[bool], r: usize| -> Vec<bool> {
            let mut out = vec![false; w];
            for (i, &bit) in v.iter().enumerate() {
                out[(i + r) % w] = bit;
            }
            out
        };
        let mut checked = 0;
        for batch in cases.chunks(64) {
            let up = self.run(&self.forward, batch, "forward");
            for ((value, amount), got) in batch.iter().zip(&up) {
                assert_eq!(
                    *got,
                    rotl(value, amount % w),
                    "forward W={w} k={} amount={amount} value={value:?}",
                    self.k
                );
            }
            let back: Vec<(Vec<bool>, usize)> =
                up.iter().cloned().zip(batch.iter().map(|(_, a)| *a)).collect();
            let restored = self.run(&self.inverse, &back, "inverse-of-forward");
            for ((value, amount), got) in batch.iter().zip(&restored) {
                assert_eq!(
                    got, value,
                    "round trip W={w} k={} amount={amount}",
                    self.k
                );
            }
            let down = self.run(&self.inverse, batch, "inverse");
            for ((value, amount), got) in batch.iter().zip(&down) {
                assert_eq!(
                    *got,
                    rotl(value, (w - amount % w) % w),
                    "inverse W={w} k={} amount={amount} value={value:?}",
                    self.k
                );
            }
            checked += batch.len();
        }
        checked
    }

    fn report_toffoli(&self, label: &str) -> usize {
        let t_fwd = tof(&self.forward);
        let t_inv = tof(&self.inverse);
        let expected = toffoli(self.w, self.k);
        assert_eq!(t_fwd, expected, "{label}: forward Toffoli");
        assert_eq!(t_inv, expected, "{label}: inverse Toffoli");
        assert_eq!(
            self.forward.len(),
            self.inverse.len(),
            "{label}: inverse is not the same gate multiset"
        );
        assert!(
            t_fwd <= self.k * self.w.saturating_sub(1),
            "{label}: exceeds the design bound k (W - 1)"
        );
        let per_layer: Vec<String> = (0..self.k)
            .map(|i| layer_toffoli(self.w, i).to_string())
            .collect();
        eprintln!(
            "PACKED_RING_ROTATE {label}: W={} k={} T={} (per layer [{}], design bound k(W-1)={})",
            self.w,
            self.k,
            t_fwd,
            per_layer.join(","),
            self.k * self.w.saturating_sub(1)
        );
        t_fwd
    }
}

fn one_hot(w: usize, j: usize) -> Vec<bool> {
    let mut v = vec![false; w];
    v[j] = true;
    v
}

pub(crate) fn run() {
    let mut rng = Rng(0x9E37_79B9_7F4A_7C15);
    let mut total = 0usize;

    // Exhaustive: every amount in [0, 2^k), every one-hot input (the
    // permutation check), plus dense pseudo-random inputs per amount.
    for &(w, k) in &[(2usize, 2usize), (4, 3), (7, 3), (8, 4), (16, 4), (33, 6)] {
        let h = Harness::build(w, k);
        let mut cases = Vec::new();
        for amount in 0..1usize << k {
            for j in 0..w {
                cases.push((one_hot(w, j), amount));
            }
            for _ in 0..4 {
                cases.push((rng.bits(w), amount));
            }
            cases.push((vec![true; w], amount));
        }
        let checked = h.check(&cases);
        h.report_toffoli("exhaustive");
        eprintln!(
            "PACKED_RING_ROTATE PASS: W={w} k={k}: {checked} cases x (forward, inverse, round trip), \
             every amount in [0,{}) incl. amount >= W (mod W), ancillae clean, phase 0",
            1usize << k
        );
        total += checked;
    }

    // Width 257 (the packed rings), 7-bit amount: one-hot permutation check for
    // every amount in [0, 128) - every single layer and every layer combination -
    // then dense random inputs.
    {
        let (w, k) = (257usize, 7usize);
        let h = Harness::build(w, k);
        let mut cases = Vec::with_capacity(w * (1 << k));
        for amount in 0..1usize << k {
            for j in 0..w {
                cases.push((one_hot(w, j), amount));
            }
        }
        let perm = h.check(&cases);
        let mut dense = Vec::with_capacity(512);
        for _ in 0..512 {
            dense.push((rng.bits(w), (rng.next() as usize) & 127));
        }
        let random = h.check(&dense);
        let t = h.report_toffoli("ring257");
        eprintln!(
            "PACKED_RING_ROTATE PASS: W=257 k=7: {perm} one-hot permutation cases (all 128 amounts) \
             + {random} dense random cases, T={t} = {} per layer",
            t / k
        );
        total += perm + random;
    }

    // Width 257, 8-bit amount (design k <= 8): dense random inputs, amounts < 256.
    {
        let (w, k) = (257usize, 8usize);
        let h = Harness::build(w, k);
        let mut dense = Vec::with_capacity(256);
        for _ in 0..256 {
            dense.push((rng.bits(w), (rng.next() as usize) & 255));
        }
        let random = h.check(&dense);
        let t = h.report_toffoli("ring257-k8");
        eprintln!(
            "PACKED_RING_ROTATE PASS: W=257 k=8: {random} dense random cases (amounts < 256), T={t} = {} per layer",
            t / k
        );
        total += random;
    }

    // The design's other representative rings: [0, W_A) at step 378 (W_A = 76,
    // 5 layers) and [256 - W_c, 257) at step 100 (W_c = 85, 86 wires, 5 layers).
    for &(w, k, label) in &[(76usize, 5usize, "step378-value"), (86, 5, "step100-coeff")] {
        let h = Harness::build(w, k);
        let mut cases = Vec::new();
        for amount in 0..1usize << k {
            for j in 0..w {
                cases.push((one_hot(w, j), amount));
            }
            cases.push((rng.bits(w), amount));
        }
        let checked = h.check(&cases);
        h.report_toffoli(label);
        total += checked;
    }

    run_review(&mut rng, &mut total);

    eprintln!("PACKED_RING_ROTATE PASS: {total} cases total, value/phase/ancilla, forward and inverse");
}

// ===========================================================================
// Adversarial review additions (2026-09-13): the ring as a sub-slice of full
// 257-wire registers with foreign neighbours on both sides, real PZ states from
// `tools/packed_prefix_model.py` in the refuters' classes (tight packing R1 gap
// 0 = cb's MSB at wire e_A; e_A = W_A with off = 0 and 1; the late-row envelope
// attainer whose merged D10+D11 amount `s + e_B` equals the ring width; first
// multiply with ca_old = 0 and e_B in [226, 256] and with e_B <= 225 = the
// all-zero window; draining rows A = 0, B = 1; terminal divisions A_new = 0;
// maximum drop d >= 15; maximum R2 gap >= 15; the tight multiply
// bl(B) + s2 + bl(cb) = 257; mid-step rows where the D11 ring [L, W_A) has A's
// bits below L and the M3 ring holds B's bits), maximum amounts on even and
// odd widths with 8- and 9-bit amounts, the reversed-slice (bit-order)
// convention, inverse-first round trips, and an op-kind audit (Fredkins only).
// Every real-state check runs forward, mirror-on-the-output (round trip),
// mirror-on-the-input and forward-on-that (the other round trip).
// ===========================================================================

/// One real PZ row: the state *before* the substep (LSB-first hex), the 1M
/// envelopes of that step, and the substep's shift data.
pub(super) struct PzRow {
    cls: &'static str,
    step: u16,
    a: &'static str,
    b: &'static str,
    ca: &'static str,
    cb: &'static str,
    wa: usize,
    wc: usize,
    /// division rows: `s_raw >= 0` and `off`; multiply rows: `s_raw = -1`, `s2 >= 0`.
    s_raw: i32,
    off: u8,
    s2: i32,
}

/// Real shrunken-PZ packed states from `tools/packed_prefix_model.py` (its exact
/// recurrence; 49 random inputs, seed 20260913, cross-checked against `pz_prefix`),
/// one per refuter class. Values are hex, LSB at wire 0; `wa`/`wc` are the 1M
/// envelopes `max(wa, wb)` / `max(wca, wcb)` of `packed_layout_results.json` at
/// that step (for the `eA_WA` rows `wa` is set to `bl(A)`: the envelope attainer).
pub(super) const PZ_ROWS: &[PzRow] = &[
    PzRow { cls: "div_gap0_off0", step: 4, a: "2fabd169c46bf1a617d560a5cf6a55a9371fb9c618ad3ee160bdc56ee78dfa9c", b: "11a4e8ef29e447c188d51cc2f2ec53b1ec615f21849dc5991c4b24d47a3a1723", ca: "1", cb: "5", wa: 255, wc: 16, s_raw: 1, off: 0, s2: -1 },
    PzRow { cls: "div_gap0_off0", step: 8, a: "c61ff8b70a36223062b271fe991ae455e5cfb830f71b3af28277bc5f319cc56", b: "542e963b940e59e82a9f5a3095aa56c8e04639e752c11e9f423a90e87204acd", ca: "b", cb: "10", wa: 254, wc: 18, s_raw: 1, off: 0, s2: -1 },
    PzRow { cls: "div_gap0_off1", step: 6, a: "11a4e8ef29e447c188d51cc2f2ec53b1ec615f21849dc5991c4b24d47a3a1723", b: "c61ff8b70a36223062b271fe991ae455e5cfb830f71b3af28277bc5f319cc56", ca: "5", cb: "b", wa: 254, wc: 17, s_raw: 1, off: 1, s2: -1 },
    PzRow { cls: "div_gap0_off1", step: 10, a: "542e963b940e59e82a9f5a3095aa56c8e04639e752c11e9f423a90e87204acd", b: "1dc2cc3fe2196e600d73bd9d6dc636c4254344625198fdb3fe029a8e4d936bc", ca: "10", cb: "2b", wa: 253, wc: 19, s_raw: 2, off: 1, s2: -1 },
    PzRow { cls: "div_eA_WA_off0", step: 0, a: "fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f", b: "2fabd169c46bf1a617d560a5cf6a55a9371fb9c618ad3ee160bdc56ee78dfa9c", ca: "0", cb: "1", wa: 256, wc: 1, s_raw: 2, off: 0, s2: -1 },
    PzRow { cls: "div_eA_WA_off0", step: 4, a: "2fabd169c46bf1a617d560a5cf6a55a9371fb9c618ad3ee160bdc56ee78dfa9c", b: "11a4e8ef29e447c188d51cc2f2ec53b1ec615f21849dc5991c4b24d47a3a1723", ca: "1", cb: "5", wa: 254, wc: 16, s_raw: 1, off: 0, s2: -1 },
    PzRow { cls: "div_eA_WA_off1", step: 1, a: "4150ba58ee503967a0aa7d68c256a95b238118e79d4b047a7d08ea4361c811bf", b: "2fabd169c46bf1a617d560a5cf6a55a9371fb9c618ad3ee160bdc56ee78dfa9c", ca: "0", cb: "1", wa: 255, wc: 11, s_raw: 1, off: 1, s2: -1 },
    PzRow { cls: "div_eA_WA_off1", step: 6, a: "11a4e8ef29e447c188d51cc2f2ec53b1ec615f21849dc5991c4b24d47a3a1723", b: "c61ff8b70a36223062b271fe991ae455e5cfb830f71b3af28277bc5f319cc56", ca: "5", cb: "b", wa: 253, wc: 17, s_raw: 1, off: 1, s2: -1 },
    PzRow { cls: "div_late_eA_WA_off0", step: 368, a: "d8b37be4a19", b: "9902ce5e5c1", ca: "3efd0a4504c51269ff12fb22815580657f781b20a32d86db54e", cb: "12e40858df7eb784e938bbd61e2ca9617c4da05fb209bdbcc8b789", wa: 44, wc: 256, s_raw: 0, off: 0, s2: -1 },
    PzRow { cls: "div_late_eA_WA_off0", step: 372, a: "3fb0ad86458", b: "19a17351d11", ca: "12e7f82983cf03d60fd8ad05d054beb982a597e16413f095366cd7", cb: "38b3f8abe71cbf3108ea15e1bed626d48198d0227a319ee7359137", wa: 42, wc: 256, s_raw: 1, off: 0, s2: -1 },
    PzRow { cls: "div_late_eA_WA_off1", step: 370, a: "9902ce5e5c1", b: "3fb0ad86458", ca: "12e40858df7eb784e938bbd61e2ca9617c4da05fb209bdbcc8b789", cb: "12e7f82983cf03d60fd8ad05d054beb982a597e16413f095366cd7", wa: 44, wc: 256, s_raw: 2, off: 1, s2: -1 },
    PzRow { cls: "div_late_eA_WA_off1", step: 378, a: "c5e58c8a5", b: "f6e19fe6", ca: "14153cbae8b2dc3a14c43c7745ad83f998d47406f2b1ffbae78afc1", cb: "14998ca46a04e4bc4ce5e9500efb8505fb5a4b3f190a76e94b2c8b55", wa: 36, wc: 256, s_raw: 4, off: 1, s2: -1 },
    PzRow { cls: "div_late", step: 370, a: "9902ce5e5c1", b: "3fb0ad86458", ca: "12e40858df7eb784e938bbd61e2ca9617c4da05fb209bdbcc8b789", cb: "12e7f82983cf03d60fd8ad05d054beb982a597e16413f095366cd7", wa: 81, wc: 256, s_raw: 2, off: 1, s2: -1 },
    PzRow { cls: "div_late", step: 372, a: "3fb0ad86458", b: "19a17351d11", ca: "12e7f82983cf03d60fd8ad05d054beb982a597e16413f095366cd7", cb: "38b3f8abe71cbf3108ea15e1bed626d48198d0227a319ee7359137", wa: 79, wc: 256, s_raw: 1, off: 0, s2: -1 },
    PzRow { cls: "div_mid_L", step: 4, a: "2fabd169c46bf1a617d560a5cf6a55a9371fb9c618ad3ee160bdc56ee78dfa9c", b: "11a4e8ef29e447c188d51cc2f2ec53b1ec615f21849dc5991c4b24d47a3a1723", ca: "1", cb: "5", wa: 255, wc: 16, s_raw: 1, off: 0, s2: -1 },
    PzRow { cls: "div_mid_L", step: 8, a: "c61ff8b70a36223062b271fe991ae455e5cfb830f71b3af28277bc5f319cc56", b: "542e963b940e59e82a9f5a3095aa56c8e04639e752c11e9f423a90e87204acd", ca: "b", cb: "10", wa: 254, wc: 18, s_raw: 1, off: 0, s2: -1 },
    PzRow { cls: "div_mid_L", step: 10, a: "542e963b940e59e82a9f5a3095aa56c8e04639e752c11e9f423a90e87204acd", b: "1dc2cc3fe2196e600d73bd9d6dc636c4254344625198fdb3fe029a8e4d936bc", ca: "10", cb: "2b", wa: 253, wc: 19, s_raw: 2, off: 1, s2: -1 },
    PzRow { cls: "div_terminal", step: 435, a: "1", b: "1", ca: "255e48f44a2b3ad8200ebaf5fb78fc67d7fba0bdb8cdb24c8da4225fcc0a800", cb: "eebe37f1a148c04da3c2e5f187cbb4ead52d6f03e612049215c92b2699a503f", wa: 45, wc: 256, s_raw: 0, off: 0, s2: -1 },
    PzRow { cls: "div_terminal", step: 452, a: "2", b: "1", ca: "45d281e21c61c2211c824ead4104128dc16cbd934a15d60fd3945f82471bd285", cb: "5d16bf0ef1cf1eef71bed8a95f7df6b91f49a1365af514f81635d03e5c7214d5", wa: 38, wc: 256, s_raw: 1, off: 0, s2: -1 },
    PzRow { cls: "div_dmax", step: 335, a: "28979b4554d1cbd", b: "28976a5313aa45c", ca: "26d471ff0b35266478681e959176f6fa699e18a6ebd6e09e2", cb: "13b235fab394542d7d49329fc5b905b3d03b1098ac63d04433", wa: 97, wc: 236, s_raw: 0, off: 0, s2: -1 },
    PzRow { cls: "div_dmax", step: 347, a: "1a8c331dc80db8d", b: "6a2fda3e8540eb", ca: "a7ab2c83220d076950b306e663be931f3f6a9383905086da9", cb: "328eb571a5f7be2ea442530ed3fb832f8512eb80c684052d1c", wa: 91, wc: 243, s_raw: 2, off: 0, s2: -1 },
    PzRow { cls: "div_s0", step: 1, a: "4150ba58ee503967a0aa7d68c256a95b238118e79d4b047a7d08ea4361c811bf", b: "2fabd169c46bf1a617d560a5cf6a55a9371fb9c618ad3ee160bdc56ee78dfa9c", ca: "0", cb: "1", wa: 255, wc: 11, s_raw: 1, off: 1, s2: -1 },
    PzRow { cls: "div_smax", step: 308, a: "1c0bea7f74f2535578ed", b: "178f6d3e3ccd13aa6", ca: "2a2c1be3ec83504c467c42c41f56a254b8e320032cd6b", cb: "9208c6e71adde5151724605ab06485936c75c57477d61", wa: 111, wc: 222, s_raw: 12, off: 0, s2: -1 },
    PzRow { cls: "mul_first_eB226", step: 2, a: "11a4e8ef29e447c188d51cc2f2ec53b1ec615f21849dc5991c4b24d47a3a1723", b: "2fabd169c46bf1a617d560a5cf6a55a9371fb9c618ad3ee160bdc56ee78dfa9c", ca: "0", cb: "1", wa: 255, wc: 11, s_raw: -1, off: 0, s2: 0 },
    PzRow { cls: "mul_first_eB226", step: 2, a: "d1e754bd1747c5df8a72d7e21a0a319628dcd6a1ada17e7f557e0f51766921", b: "550f5d8e6ba2e81360272f0d5f4ca744cdf2610dca1b74d5d58e2b4fe4d8865a", ca: "0", cb: "1", wa: 255, wc: 11, s_raw: -1, off: 0, s2: 0 },
    PzRow { cls: "mul_first_eB226", step: 2, a: "114bf366a06c8151c3fb56e7a077d44b8e62fe5430118b9017e49f2f270105d3", b: "4f91598875312a3a14018db2ca82b93c25df008e9aa4d17aa2b3caeff2ffa774", ca: "0", cb: "1", wa: 255, wc: 11, s_raw: -1, off: 0, s2: 0 },
    PzRow { cls: "mul_first_eB226", step: 1, a: "ae68b9036e2023e2eac0b09d319c51ac1c0954250e39849f901e40bb52b3c7", b: "7fa8cba37e48efee0e8a9fa7b16731d729f1fb55ed78e33db037f0df2256a434", ca: "0", cb: "1", wa: 255, wc: 11, s_raw: -1, off: 0, s2: 1 },
    PzRow { cls: "mul_first_eB_le225", step: 56, a: "fffffffffffffffffffffffffffffedcba98ffffff01234196", b: "100000000000000000000000000000000000000000001234567", ca: "0", cb: "1", wa: 235, wc: 55, s_raw: -1, off: 0, s2: 0 },
    PzRow { cls: "mul_first_eB_le225", step: 32, a: "ffffffffffffffffffffffffffffffffffffffff21524110deadbb1e", b: "1000000000000000000000000000000000000000000000000deadbeef", ca: "0", cb: "1", wa: 245, wc: 38, s_raw: -1, off: 0, s2: 0 },
    PzRow { cls: "mul_gapmax", step: 346, a: "1380bfc1b2f", b: "30f24127861", ca: "13b235fab394542d7d49329fc5b905b3d03b1098ac63d04433", cb: "64e855057298f749b9f47f0835b48bf2b7c13485ccb07f5ee1", wa: 92, wc: 243, s_raw: -1, off: 0, s2: 0 },
    PzRow { cls: "mul_gapmax", step: 347, a: "1380bfc1b2f", b: "30f24127861", ca: "789a8b00262d4b77373db1a7fb6d91a687fc451e79144fa314", cb: "64e855057298f749b9f47f0835b48bf2b7c13485ccb07f5ee1", wa: 91, wc: 243, s_raw: -1, off: 0, s2: 2 },
    PzRow { cls: "mul_mid_zone", step: 3, a: "11a4e8ef29e447c188d51cc2f2ec53b1ec615f21849dc5991c4b24d47a3a1723", b: "2fabd169c46bf1a617d560a5cf6a55a9371fb9c618ad3ee160bdc56ee78dfa9c", ca: "1", cb: "1", wa: 255, wc: 16, s_raw: -1, off: 0, s2: 2 },
    PzRow { cls: "mul_mid_zone", step: 5, a: "c61ff8b70a36223062b271fe991ae455e5cfb830f71b3af28277bc5f319cc56", b: "11a4e8ef29e447c188d51cc2f2ec53b1ec615f21849dc5991c4b24d47a3a1723", ca: "1", cb: "5", wa: 254, wc: 17, s_raw: -1, off: 0, s2: 1 },
    PzRow { cls: "mul_mid_zone", step: 9, a: "1dc2cc3fe2196e600d73bd9d6dc636c4254344625198fdb3fe029a8e4d936bc", b: "542e963b940e59e82a9f5a3095aa56c8e04639e752c11e9f423a90e87204acd", ca: "b", cb: "10", wa: 253, wc: 19, s_raw: -1, off: 0, s2: 1 },
    PzRow { cls: "mul_drain", step: 436, a: "0", b: "1", ca: "255e48f44a2b3ad8200ebaf5fb78fc67d7fba0bdb8cdb24c8da4225fcc0a800", cb: "eebe37f1a148c04da3c2e5f187cbb4ead52d6f03e612049215c92b2699a503f", wa: 44, wc: 256, s_raw: -1, off: 0, s2: 0 },
    PzRow { cls: "mul_drain", step: 437, a: "0", b: "1", ca: "1141c80e5eb73fb25c3d1a0e78344b152ad290fc19edfb6dea36d4d8665af83f", cb: "eebe37f1a148c04da3c2e5f187cbb4ead52d6f03e612049215c92b2699a503f", wa: 44, wc: 256, s_raw: -1, off: 0, s2: 4 },
    PzRow { cls: "mul_tight", step: 3, a: "11a4e8ef29e447c188d51cc2f2ec53b1ec615f21849dc5991c4b24d47a3a1723", b: "2fabd169c46bf1a617d560a5cf6a55a9371fb9c618ad3ee160bdc56ee78dfa9c", ca: "1", cb: "1", wa: 255, wc: 16, s_raw: -1, off: 0, s2: 2 },
    PzRow { cls: "mul_tight", step: 5, a: "c61ff8b70a36223062b271fe991ae455e5cfb830f71b3af28277bc5f319cc56", b: "11a4e8ef29e447c188d51cc2f2ec53b1ec615f21849dc5991c4b24d47a3a1723", ca: "1", cb: "5", wa: 254, wc: 17, s_raw: -1, off: 0, s2: 1 },
    PzRow { cls: "mul_s2max", step: 319, a: "1662a71f4fefda1cb", b: "178f6d3e3ccd13aa6", ca: "1bc8ae15d22adbb6779b22d76bae13919efc342f96bd5396", cb: "9208c6e71adde5151724605ab06485936c75c57477d61", wa: 105, wc: 227, s_raw: -1, off: 0, s2: 12 },
    PzRow { cls: "mul_s2zero", step: 7, a: "542e963b940e59e82a9f5a3095aa56c8e04639e752c11e9f423a90e87204acd", b: "c61ff8b70a36223062b271fe991ae455e5cfb830f71b3af28277bc5f319cc56", ca: "5", cb: "b", wa: 254, wc: 18, s_raw: -1, off: 0, s2: 0 },
];

/// 257-bit vector (LSB first) from LSB-first hex.
fn hex_bits(h: &str) -> Vec<bool> {
    let mut v = vec![false; 257];
    for (i, ch) in h.bytes().rev().enumerate() {
        let d = (ch as char).to_digit(16).expect("hex digit") as usize;
        for j in 0..4 {
            if (d >> j) & 1 == 1 {
                let bit = 4 * i + j;
                assert!(bit < 257, "value wider than 257 bits");
                v[bit] = true;
            }
        }
    }
    v
}

fn bitlen(v: &[bool]) -> usize {
    v.iter().rposition(|&b| b).map_or(0, |p| p + 1)
}

/// The packed register `[value LSB at wire 0 | gap | coeff bit j at wire 256 - j]`.
fn pack(value: &[bool], coeff: &[bool]) -> Vec<bool> {
    let (ev, ec) = (bitlen(value), bitlen(coeff));
    assert!(ev + ec <= 257, "packing invariant bl(value) + bl(coeff) <= 257");
    let mut r = vec![false; 257];
    r[..ev].copy_from_slice(&value[..ev]);
    for j in 0..ec {
        r[256 - j] = coeff[j];
    }
    r
}

/// `value - (other << s)` on 257-bit vectors; the caller guarantees no borrow out.
fn sub_shifted(value: &[bool], other: &[bool], s: usize) -> Vec<bool> {
    let mut out = vec![false; 257];
    let mut borrow = false;
    for w in 0..257 {
        let x = value[w];
        let y = if w >= s { other[w - s] } else { false };
        out[w] = x ^ y ^ borrow;
        borrow = (!x & (y | borrow)) | (x & y & borrow);
    }
    assert!(!borrow, "sub_shifted: negative result");
    out
}

/// Classical model of one `ring_rotate` call on the slice `[lo, hi)` of `v`
/// (handed over in descending wire order when `rev`): up by `amount mod W`
/// when `!inverse`, down otherwise.
fn rot_slice(v: &mut [bool], lo: usize, hi: usize, rev: bool, amount: usize, inverse: bool) {
    let w = hi - lo;
    if w < 2 {
        return;
    }
    let r = amount % w;
    let r = if inverse != rev { (w - r) % w } else { r };
    let old: Vec<bool> = v[lo..hi].to_vec();
    for (i, &bit) in old.iter().enumerate() {
        v[lo + (i + r) % w] = bit;
    }
}

/// One rotation of a plan on register `reg` (0 = R1, 1 = R2), slice `[lo, hi)`
/// (`rev`: handed to `ring_rotate` in descending wire order), amount register
/// `amt`, direction `inverse`.
#[derive(Clone, Copy)]
struct Rot {
    reg: usize,
    lo: usize,
    hi: usize,
    rev: bool,
    amt: usize,
    inverse: bool,
}

/// Two full 257-wire registers plus amount registers; `forward` is the plan,
/// `mirror` the plan reversed with every direction flipped (the backward driver).
struct Full {
    forward: Vec<Op>,
    mirror: Vec<Op>,
    regs: [Vec<QubitId>; 2],
    amts: Vec<Vec<QubitId>>,
    nq: usize,
}

impl Full {
    fn build(plan: &[Rot], ks: &[usize]) -> Self {
        let mut built = Vec::new();
        for mirror in [false, true] {
            let mut c = Circuit::new();
            let mut r1 = c.alloc_qreg_bits("R1", 257);
            let mut r2 = c.alloc_qreg_bits("R2", 257);
            let amts: Vec<Vec<QReg>> = ks
                .iter()
                .enumerate()
                .map(|(i, &k)| c.alloc_qreg_bits(&format!("amt{i}"), k))
                .collect();
            let regs = [ids(&r1), ids(&r2)];
            let amt_ids: Vec<Vec<QubitId>> = amts.iter().map(|a| ids(a)).collect();
            let order: Vec<Rot> = if mirror {
                plan.iter().rev().map(|r| Rot { inverse: !r.inverse, ..*r }).collect()
            } else {
                plan.to_vec()
            };
            for rot in order {
                let reg = if rot.reg == 0 { &mut r1 } else { &mut r2 };
                // QReg is not Clone: move the slice out, rotate, move it back.
                let mut ring: Vec<QReg> = reg.drain(rot.lo..rot.hi).collect();
                if rot.rev {
                    ring.reverse();
                }
                ring_rotate(&mut c, &ring, &amts[rot.amt], rot.inverse);
                if rot.rev {
                    ring.reverse();
                }
                drop(reg.splice(rot.lo..rot.lo, ring));
            }
            assert_eq!(ids(&r1), regs[0]);
            assert_eq!(ids(&r2), regs[1]);
            let (nq, _, _, _) = analyze_ops(c.b.ops.iter());
            built.push((c.b.ops.clone(), regs, amt_ids, nq as usize));
        }
        let (mirror, regs1, amts1, nq1) = built.pop().unwrap();
        let (forward, regs, amts, nq0) = built.pop().unwrap();
        assert_eq!(regs, regs1);
        assert_eq!(amts, amts1);
        assert_eq!(forward.len(), mirror.len(), "mirror is not the same gate multiset");
        Self {
            forward,
            mirror,
            regs,
            amts,
            nq: nq0.max(nq1).max(514 + ks.iter().sum::<usize>()),
        }
    }

    /// Apply `ops` to one state; returns (R1, R2) read back. Asserts phase 0,
    /// amount wires unchanged, everything else zero.
    fn run(&self, ops: &[Op], r1: &[bool], r2: &[bool], amounts: &[usize], what: &str) -> (Vec<bool>, Vec<bool>) {
        let mut seed = Shake256::default();
        seed.update(b"packed-ring-rotate-review-v1");
        let mut xof = seed.finalize_xof();
        let mut sim = Simulator::new(self.nq, 1, &mut xof);
        for (reg, val) in self.regs.iter().zip([r1, r2]) {
            assert_eq!(val.len(), 257);
            for (w, &bit) in val.iter().enumerate() {
                if bit {
                    *sim.qubit_mut(reg[w]) |= 1;
                }
            }
        }
        for (a, &val) in self.amts.iter().zip(amounts) {
            assert!(val < 1usize << a.len(), "{what}: amount {val} does not fit {} bits", a.len());
            for (i, &id) in a.iter().enumerate() {
                if (val >> i) & 1 == 1 {
                    *sim.qubit_mut(id) |= 1;
                }
            }
        }
        sim.apply_iter(ops.iter());
        assert_eq!(sim.phase & 1, 0, "{what}: phase garbage");
        for (a, &val) in self.amts.iter().zip(amounts) {
            for (i, &id) in a.iter().enumerate() {
                assert_eq!(sim.qubit(id) & 1, ((val >> i) & 1) as u64, "{what}: amount wire {i} changed");
            }
        }
        let out1: Vec<bool> = self.regs[0].iter().map(|&id| sim.qubit(id) & 1 == 1).collect();
        let out2: Vec<bool> = self.regs[1].iter().map(|&id| sim.qubit(id) & 1 == 1).collect();
        for &id in self.regs.iter().flatten().chain(self.amts.iter().flatten()) {
            *sim.qubit_mut(id) = 0;
        }
        assert!(sim.qubits.iter().all(|&q| q & 1 == 0), "{what}: dirty scratch");
        (out1, out2)
    }

    /// Forward on the input = the classical plan; mirror on that output
    /// restores the input; mirror on the input = the classical inverse plan;
    /// forward on that restores the input. Returns the forward output.
    fn check(&self, plan: &[Rot], r1: &[bool], r2: &[bool], amounts: &[usize], what: &str) -> (Vec<bool>, Vec<bool>) {
        let mut exp = [r1.to_vec(), r2.to_vec()];
        for rot in plan {
            rot_slice(&mut exp[rot.reg], rot.lo, rot.hi, rot.rev, amounts[rot.amt], rot.inverse);
        }
        let (o1, o2) = self.run(&self.forward, r1, r2, amounts, what);
        assert!(o1 == exp[0] && o2 == exp[1], "{what}: forward plan value mismatch");
        let (b1, b2) = self.run(&self.mirror, &o1, &o2, amounts, what);
        assert!(b1 == r1 && b2 == r2, "{what}: mirror on the forward output does not restore the input");
        let mut expi = [r1.to_vec(), r2.to_vec()];
        for rot in plan.iter().rev() {
            rot_slice(&mut expi[rot.reg], rot.lo, rot.hi, rot.rev, amounts[rot.amt], !rot.inverse);
        }
        let (i1, i2) = self.run(&self.mirror, r1, r2, amounts, what);
        assert!(i1 == expi[0] && i2 == expi[1], "{what}: mirror plan value mismatch");
        let (f1, f2) = self.run(&self.forward, &i1, &i2, amounts, what);
        assert!(f1 == r1 && f2 == r2, "{what}: forward on the mirror output does not restore the input");
        (o1, o2)
    }

    /// Toffoli count of the forward plan, asserted equal to the mirror's and to
    /// the per-call model `toffoli(W, k)` summed over the plan; returns it.
    fn toffoli_checked(&self, plan: &[Rot], ks: &[usize], what: &str) -> usize {
        let expected: usize = plan.iter().map(|r| toffoli(r.hi - r.lo, ks[r.amt])).sum();
        let bound: usize = plan.iter().map(|r| ks[r.amt] * (r.hi - r.lo).saturating_sub(1)).sum();
        let t = tof(&self.forward);
        assert_eq!(t, expected, "{what}: forward Toffoli != model");
        assert_eq!(tof(&self.mirror), expected, "{what}: mirror Toffoli != model");
        assert!(t <= bound, "{what}: exceeds the design bound k (W - 1) summed");
        op_audit(&self.forward, what);
        op_audit(&self.mirror, what);
        t
    }
}

/// Only Fredkins are emitted: every op is CX or CCX and #CX = 2 #CCX
/// (no measurement, reset, phase or classical op anywhere).
fn op_audit(ops: &[Op], what: &str) {
    let ccx = ops.iter().filter(|op| matches!(op.kind, OperationType::CCX)).count();
    let cx = ops.iter().filter(|op| matches!(op.kind, OperationType::CX)).count();
    assert_eq!(ccx + cx, ops.len(), "{what}: op kinds other than CX/CCX emitted");
    assert_eq!(cx, 2 * ccx, "{what}: not a pure Fredkin sequence");
}

fn rot(reg: usize, lo: usize, hi: usize, amt: usize, inverse: bool) -> Rot {
    Rot { reg, lo, hi, rev: false, amt, inverse }
}

/// The design's ring sequences on real PZ states (section 3.1 D3/D5/D11/D10,
/// section 3.2 M1/M3/M9/M11) with the design's placement claims asserted.
fn pz_rows(total: &mut usize) {
    let mut n_claims = 0usize;
    let mut classes: Vec<&str> = Vec::new();
    for row in PZ_ROWS {
        if !classes.contains(&row.cls) {
            classes.push(row.cls);
        }
        let (a, b, ca, cb) = (hex_bits(row.a), hex_bits(row.b), hex_bits(row.ca), hex_bits(row.cb));
        let (e_a, e_b, e_ca, e_cb) = (bitlen(&a), bitlen(&b), bitlen(&ca), bitlen(&cb));
        assert!(e_a + e_cb <= 257 && e_b + e_ca <= 257, "{}: packing invariant", row.cls);
        let r1 = pack(&a, &cb);
        let r2 = pack(&b, &ca);
        let what = format!("{} step {}", row.cls, row.step);
        if row.s_raw >= 0 {
            // ------------------------------------------------ division row
            let w = row.wa;
            let (s_raw, off) = (row.s_raw as usize, row.off as usize);
            let s = s_raw - off;
            let e = e_b + off;
            assert!(e_a <= w && e_b <= e_a && e_a == e_b + s_raw, "{what}: row data");
            assert!(s_raw < 32, "{what}: s_raw outside the 5-bit s_rot");
            let lo_b = w.saturating_sub(78);
            let l = lo_b.saturating_sub(32);
            let t7 = w - e_b;
            assert!(t7 < 128 && (l > 0 || s + e_b < 128), "{what}: 7-bit amounts (t7, and s + e_B on merged rows)");
            // D3 (down by s_raw) then D5 (up by off): the s-frame.
            let plan_a = [rot(0, 0, w, 0, true), rot(0, 0, w, 1, false)];
            let ha = Full::build(&plan_a, &[5, 1]);
            let (s1, s1_r2) = ha.check(&plan_a, &r1, &r2, &[s_raw, off], &format!("{what} D3+D5"));
            let t_a = ha.toffoli_checked(&plan_a, &[5, 1], &format!("{what} D3+D5"));
            *total += 1;
            assert_eq!(s1_r2, r2);
            // 2.1 claims: A>>s on the field [0, E), A's low s bits on [W-s, W),
            // wires >= W untouched, cb's in-ring bits moved down by s.
            for j in 0..e {
                assert_eq!(s1[j], a[j + s], "{what}: A>>s bit {j}");
            }
            for j in 0..s {
                assert_eq!(s1[w - s + j], a[j], "{what}: A's low bit {j} at wire {}", w - s + j);
            }
            assert_eq!(&s1[w..], &r1[w..], "{what}: wires >= W_A touched");
            for x in (257 - e_cb).max(s)..w {
                assert_eq!(s1[x - s], r1[x], "{what}: cb's in-ring bit at wire {x}");
            }
            // The first wire above the field, E, holds the original wire e_A mod W:
            // a gap zero, cb's MSB (R1 gap 0) or A's bit 0 (e_A = W_A) - refuter 1's
            // foreign bit; the window top e_B - 1 = E - 1 - off is below it.
            if e < w {
                let kind = if e_a == w {
                    "A bit 0"
                } else if e_a + e_cb == 257 {
                    "cb MSB"
                } else {
                    "gap zero"
                };
                assert_eq!(s1[e], r1[e_a % w], "{what}: wire E");
                match kind {
                    "cb MSB" => assert!(s1[e], "{what}: cb's MSB at wire E must be set"),
                    "A bit 0" => assert_eq!(s1[e], a[0], "{what}: A's bit 0 must sit at wire E"),
                    _ => assert!(!s1[e], "{what}: wire E should be a gap zero"),
                }
                n_claims += 1;
            }
            n_claims += 4;
            // D7 classically: the field [0, E) := A_new >> s.
            let a_new = sub_shifted(&a, &b, s);
            let d = e_a - bitlen(&a_new);
            assert!(d >= 1, "{what}: d >= 1 always");
            let mut s2 = s1.clone();
            for j in 0..e {
                s2[j] = a_new[j + s];
            }
            // D11: up by t7 on [L, W).
            let plan_b1 = [rot(0, l, w, 0, false)];
            let hb1 = Full::build(&plan_b1, &[7]);
            let (s3, _) = hb1.check(&plan_b1, &s2, &r2, &[t7], &format!("{what} D11 up"));
            let t_b1 = hb1.toffoli_checked(&plan_b1, &[7], &format!("{what} D11 up"));
            *total += 1;
            // window [W-32, W) = s-frame wires [e_B-32, e_B) (mod the ring)
            let ring = w - l;
            assert!(w >= 32, "{what}: W_A < 32: the 32-window does not fit the ring (design 2.4 is silent; the T-model widens the ring to 32)");
            for j in 0..32 {
                let src = l + (e_b as i64 - 32 + j as i64 - l as i64).rem_euclid(ring as i64) as usize;
                assert_eq!(s3[w - 32 + j], s2[src], "{what}: window position {j}");
            }
            n_claims += 1;
            // R's MSB at W-1+off-d with only R's own zeros above it: the top-down
            // first 1 of the window is k = 31 + off - d (not on terminal rows).
            if bitlen(&a_new) != 0 {
                assert!(d <= 31 + off, "{what}: drop_bound miss d={d}");
                let k = 31 + off - d;
                let first = (0..32).rev().find(|&j| s3[w - 32 + j]);
                assert_eq!(first, Some(k), "{what}: D11 window top-down first 1 (d={d}, off={off})");
                n_claims += 1;
            }
            // D11 back and D10 (mid rows) or the merged 7-layer rotation by s + e_B (late rows).
            let (plan_b2, ks2, am2): (Vec<Rot>, Vec<usize>, Vec<usize>) = if l == 0 {
                (vec![rot(0, 0, w, 0, false)], vec![7], vec![s + e_b])
            } else {
                (vec![rot(0, l, w, 0, true), rot(0, 0, w, 1, false)], vec![7, 5], vec![t7, s])
            };
            let hb2 = Full::build(&plan_b2, &ks2);
            let (s5, _) = hb2.check(&plan_b2, &s3, &r2, &am2, &format!("{what} D11 back + D10"));
            let t_b2 = hb2.toffoli_checked(&plan_b2, &ks2, &format!("{what} D11 back + D10"));
            *total += 1;
            // The LSB frame: R1 = [A_new | zeros | cb] exactly.
            assert_eq!(s5, pack(&a_new, &cb), "{what}: LSB frame after D10 is not [A_new | cb]");
            n_claims += 1;
            eprintln!(
                "PACKED_RING_ROTATE pz {what}: W_A={w} L={l} e_A={e_a} e_B={e_b} e_cb={e_cb} s_raw={s_raw} off={off} d={d} \
                 merged={} T: D3+D5={t_a} D11up={t_b1} D11back+D10={t_b2} (design {} + {} + {})",
                l == 0,
                5 * (w - 1) + (w - 1),
                7 * (w - l - 1),
                if l == 0 { 7 * (w - 1) } else { 7 * (w - l - 1) + 5 * (w - 1) }
            );
        } else {
            // ------------------------------------------------ multiply row
            let s2 = row.s2 as usize;
            let (w, wc) = (row.wa, row.wc);
            assert!(e_ca <= wc && e_cb <= wc && e_b <= w && s2 < 32, "{what}: row data");
            assert!(e_b + s2 + e_cb <= 257, "{what}: multiply fit theorem");
            let lo_b = w.saturating_sub(78);
            let t = (w + 32).min(257);
            assert!(e_b >= lo_b, "{what}: e_B below lo_B (width miss)");
            let t7 = e_b - lo_b;
            assert!(t7 < 128);
            // M1: down by t7 on R2[lo_B, T).
            let plan_m1 = [rot(1, lo_b, t, 0, true)];
            let h1 = Full::build(&plan_m1, &[7]);
            let (m1_r1, m1) = h1.check(&plan_m1, &r1, &r2, &[t7], &format!("{what} M1"));
            let t_m1 = h1.toffoli_checked(&plan_m1, &[7], &format!("{what} M1"));
            *total += 1;
            assert_eq!(m1_r1, r1);
            // window [lo_B, lo_B+32) = original wires [e_B, e_B+32), wrapping at T into lo_B
            let win: Vec<bool> = (0..32).map(|j| m1[lo_b + j]).collect();
            for j in 0..32 {
                assert_eq!(win[j], r2[lo_b + (t7 + j) % (t - lo_b)], "{what}: M1 window position {j}");
            }
            let lowest = win.iter().position(|&x| x);
            let gap = 257 - e_b - e_ca;
            if e_ca != 0 {
                if gap < 32 {
                    assert_eq!(lowest, Some(gap), "{what}: M1 lowest 1 must be ca's MSB at gap {gap}");
                } else {
                    assert_eq!(lowest, None, "{what}: gap_bound row must read an all-zero window");
                }
            } else {
                // ca_old = 0: all-zero window (e_B <= 225) or B's wrapped bits at >= 257 - e_B
                if e_b <= 225 {
                    assert_eq!(lowest, None, "{what}: first multiply with e_B <= 225 must see an all-zero window");
                } else {
                    assert!(lowest.map_or(true, |p| p >= 257 - e_b), "{what}: ca_old = 0 lowest 1 below 257 - e_B");
                }
            }
            n_claims += 2;
            // M3: up by s2 on the ring [256-W_c, 257).
            let lo_c = 256 - wc;
            let plan_m3 = [rot(1, lo_c, 257, 0, false)];
            let h3 = Full::build(&plan_m3, &[5]);
            let (_, m3) = h3.check(&plan_m3, &r1, &r2, &[s2], &format!("{what} M3"));
            let t_m3 = h3.toffoli_checked(&plan_m3, &[5], &format!("{what} M3"));
            *total += 1;
            // ca>>s2 at wires 256-j; ca's low s2 bits at the ring bottom; B's in-ring bits up by s2
            for j in 0..e_ca.saturating_sub(s2) {
                assert_eq!(m3[256 - j], ca[j + s2], "{what}: (ca>>s2) bit {j}");
            }
            for j in 0..s2 {
                assert_eq!(m3[lo_c + s2 - 1 - j], ca[j], "{what}: ca's low bit {j} at the ring bottom");
            }
            for x in lo_c..e_b {
                assert_eq!(m3[x + s2], r2[x], "{what}: B's in-ring bit at wire {x}");
            }
            assert_eq!(&m3[..lo_c], &r2[..lo_c], "{what}: wires below the M3 ring touched");
            n_claims += 3;
            // The same ring handed over in bit order (wire 256 first) and rotated
            // DOWN must give the same state and the same Toffoli count.
            let plan_m3r = [Rot { reg: 1, lo: lo_c, hi: 257, rev: true, amt: 0, inverse: true }];
            let h3r = Full::build(&plan_m3r, &[5]);
            let (_, m3r) = h3r.check(&plan_m3r, &r1, &r2, &[s2], &format!("{what} M3 reversed slice"));
            assert_eq!(m3r, m3, "{what}: reversed-slice rotation != wire-order rotation");
            assert_eq!(h3r.toffoli_checked(&plan_m3r, &[5], &format!("{what} M3 rev")), t_m3);
            *total += 1;
            // M3 + M9 (1 layer by carry) + M11 (down by s2 + carry) is the identity.
            for carry in 0..2usize {
                let plan = [rot(1, lo_c, 257, 0, false), rot(1, lo_c, 257, 1, false), rot(1, lo_c, 257, 2, true)];
                let h = Full::build(&plan, &[5, 1, 5]);
                let (_, out) = h.check(&plan, &r1, &r2, &[s2, carry, s2 + carry], &format!("{what} M3+M9+M11 carry {carry}"));
                assert_eq!(out, r2, "{what}: M3+M9+M11 (carry {carry}) is not the identity");
                h.toffoli_checked(&plan, &[5, 1, 5], &format!("{what} M3+M9+M11"));
                *total += 1;
            }
            n_claims += 1;
            eprintln!(
                "PACKED_RING_ROTATE pz {what}: W_A={w} W_c={wc} lo_B={lo_b} T={t} e_B={e_b} e_ca={e_ca} e_cb={e_cb} s2={s2} gap={gap} \
                 M1 lowest1={lowest:?} T: M1={t_m1} M3={t_m3} (design M1 {} M3 {} per 2.1, {} per the 3.2 table)",
                7 * (t - lo_b - 1),
                5 * wc,
                5 * (wc + 1)
            );
        }
    }
    eprintln!(
        "PACKED_RING_ROTATE PASS: {} real PZ rows from tools/packed_prefix_model.py in {} classes [{}], {n_claims} design placement claims",
        PZ_ROWS.len(),
        classes.len(),
        classes.join(", ")
    );
}

/// The ring as a sub-slice of a full register: foreign bits on both
/// neighbours (wires L-1 and T), random / all-ones / all-zero registers,
/// amounts 0, 1, W-1, W, W+1, 2^k-1 and random.
fn sub_slice_neighbours(rng: &mut Rng, total: &mut usize) {
    for &(lo, hi, k) in &[
        (0usize, 76usize, 7usize),
        (0, 32, 7),
        (100, 132, 7),
        (29, 108, 7),
        (171, 257, 7),
        (225, 257, 5),
        (0, 257, 8),
        (0, 1, 7),
        (5, 5, 7),
        (255, 257, 3),
        (128, 129, 1),
    ] {
        let w = hi - lo;
        let plan = [rot(0, lo, hi, 0, false)];
        let h = Full::build(&plan, &[k]);
        let mask = (1usize << k) - 1;
        let mut amounts = vec![0usize, 1 & mask, w.saturating_sub(1) & mask, w & mask, (w + 1) & mask, mask];
        for _ in 0..6 {
            amounts.push((rng.next() as usize) & mask);
        }
        for &amount in &amounts {
            let what = format!("sub-slice [{lo},{hi}) k={k} amount={amount}");
            let mut r1 = rng.bits(257);
            let r2 = rng.bits(257);
            if lo > 0 {
                r1[lo - 1] = true;
            }
            if hi < 257 {
                r1[hi] = true;
            }
            h.check(&plan, &r1, &r2, &[amount], &what);
            h.check(&plan, &vec![true; 257], &vec![true; 257], &[amount], &what);
            h.check(&plan, &vec![false; 257], &vec![false; 257], &[amount], &what);
            *total += 3;
        }
        let t = h.toffoli_checked(&plan, &[k], &format!("sub-slice [{lo},{hi}) k={k}"));
        if w < 2 {
            assert!(h.forward.is_empty() && h.mirror.is_empty(), "width {w} ring must emit nothing");
        }
        eprintln!(
            "PACKED_RING_ROTATE sub-slice [{lo},{hi}) k={k}: T={t}, {} amounts x 3 registers, neighbours untouched",
            amounts.len()
        );
    }
}

/// Maximum amounts on even, odd and power-of-two widths with 8- and 9-bit
/// amounts (every amount in [0, 2^k), one-hot inputs), plus the upper half of
/// the 8-bit amounts on width 257 that the author's k=8 case only sampled.
fn max_amounts(rng: &mut Rng, total: &mut usize) {
    for &(w, k, label, lo_amt) in &[
        (256usize, 8usize, "even256-k8", 0usize),
        (255, 8, "odd255-k8", 0),
        (128, 8, "pow2-128-k8", 0),
        (64, 7, "pow2-64-k7", 0),
        (257, 8, "ring257-k8-upper", 128),
    ] {
        let h = Harness::build(w, k);
        let mut cases = Vec::new();
        for amount in lo_amt..1usize << k {
            for j in 0..w {
                cases.push((one_hot(w, j), amount));
            }
            if amount % 16 == 0 || amount + 1 == 1 << k || amount + 1 == w || amount == w {
                cases.push((rng.bits(w), amount));
                cases.push((vec![true; w], amount));
            }
        }
        let checked = h.check(&cases);
        h.report_toffoli(label);
        op_audit(&h.forward, label);
        op_audit(&h.inverse, label);
        eprintln!("PACKED_RING_ROTATE PASS: {label}: {checked} cases, amounts [{lo_amt},{})", 1usize << k);
        *total += checked;
    }
    // 9-bit amount on width 257: layer 8 rotates by 256 = -1 mod 257.
    {
        let (w, k) = (257usize, 9usize);
        let h = Harness::build(w, k);
        let mut cases = Vec::new();
        for &amount in &[256usize, 257, 258, 384, 511, 300, 129] {
            for j in 0..w {
                cases.push((one_hot(w, j), amount));
            }
            cases.push((rng.bits(w), amount));
        }
        let checked = h.check(&cases);
        h.report_toffoli("ring257-k9");
        eprintln!("PACKED_RING_ROTATE PASS: ring257-k9: {checked} cases (amounts >= 256 incl. 256 = down by 1, 257 = identity)");
        *total += checked;
    }
}

fn run_review(rng: &mut Rng, total: &mut usize) {
    sub_slice_neighbours(rng, total);
    max_amounts(rng, total);
    pz_rows(total);
}
